### ISSUE TITLE
Update sitemap

### ISSUE THREAD

**Issue by TylerSehr** [zeta-chain/docs#253]
Sitemap is out of date, leaving out key pages. For example:

https://www.zetachain.com/docs/reference/contracts/

is not present in:

https://www.zetachain.com/docs/sitemap.xml/

**Comment by fadeev** [comment]
The URL is in the sitemap, it's just the entries in the sitemap don't have `www` subdomain. It's never been an issue, because URLs are resolved correctly. I'll look into the deployment config and see if we need to change a domain there.

<img width="953" alt="Screenshot 2024-02-12 at 18 29 45" src="https://github.com/zeta-chain/docs/assets/332151/9aaba554-4793-49f9-a942-762bef0610cb">

**Comment by TylerSehr** [comment]
Sorry, that was a bad example. The sitemap does appear to be updated since I saw it last, previously each url was structured like this: https://docs.zetachain.com/architecture/zetacored/zetacored_add-genesis-account/

Causing it to resolve to the docs homepage. 

This appears to be fixed now, Thank you!



Additional note, and I'll post an issue for it on the appropriate repo: 

https://www.zetachain.com/sitemaps/sitemap.xml

A large number of these sitemap entries resolve to 404

**Comment by fadeev** [comment]
@TylerSehr thanks for letting us know, will report this to the frontend team!
