### ISSUE TITLE
Task file name `interact` and command `withdraw` not consistent in Withdraw tutorial

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/docs#76]
In the Withdraw tutorial: https://www.zetachain.com/docs/developers/omnichain/tutorials/withdraw/#creating-the-contract

The following command will create a task named `interact.ts` to interact with the contract
```
npx hardhat omnichain Withdraw recipient
```
But later the tuto shows the following command that tries to call the task `withdraw` that then doesn't exist.
```
npx hardhat withdraw --network goerli_testnet --amount 0.5 --contract 0x5E3229522BeFD3D9CD422Fd91f4273ed4EB2639a --recipient 0x2c2d7aF555156eFB8Bfc3eBB0C41fE57D4D1C7c4
```

Either the `omnichain Withdraw` command should generate a `withdraw.ts` file or the command to interact should be corrected into `npx hardhat interact`.
I would suggest the former fix since `withdraw.ts` would be more precise for the task name.

**Comment by fadeev** [comment]
Good catch! https://github.com/zeta-chain/docs/pull/79

The reason I'm using `interact` (which I also don't particularly like) is because it's part of the template, so it's the same for all examples. I suppose what we can do is use the contracts name as the name for the default task to interact with the contract.

```
npx hardhat omnichain FooContract
```

Would create `tasks/foocontract.ts`.
