### ISSUE TITLE
Migrate to use templating: Counter

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#93]

**Comment by 1337-ishaan** [comment]
Hey @fadeev, 
The steps that would be needed to migrate as per my understanding would be to initialize the contract in template using

- `npx hardhat messaging CrossChainCounter messageType:bytes32 messageFrom:address`

The messageType parameter would be useful, because incase of situations where there are 2 or more possibilites it can act as the trigger key on the basis of which the contract decides which function to stack.

Let me know your views on this.

**Comment by 1337-ishaan** [comment]
@fadeev, The proposed solution here is:

- Initializing the contract using:  `npx hardhat messaging CrossChainCounter`

Also just one suggestion, could we not directly call this using `msg.sender`, rather than passing it as a parameter? It may save us some gas, something like 

`counter[msg.sender]++`

![image](https://github.com/zeta-chain/docs/assets/64636222/c9063913-cadb-4f7a-bf79-b333f11ea139)

Let me know your views on this.

**Comment by fadeev** [comment]
@1337-ishaan unless I'm missing something important here, I'm afraid we can't.

Inside `onZetaMessage` `msg.sender` is the connector contract address. If we want the counter to be registered under the original sender from the source chain, we need to pass it in the message.

**Comment by 1337-ishaan** [comment]
@fadeev, I'll get this done and raise a PR.

**Comment by 1337-ishaan** [comment]
@fadeev, completed this in #155, kindly check.
